### ISSUE TITLE
Python 3 scripts are not working properly

### ISSUE THREAD

**Issue by xzjkya** [IVRTech/pystrix#17]
**Current Environment**

Linux 4.9.0-3-amd64 1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux
Asterisk 13.17.0
Pystrix 1.1.0

**Summary**  

Currently trying to call an AGI script written in Python 3 (3.5.3) in Asterisk. Calls to the script are done correctly, but somehow the script stops in a 'everlasting loop' (possibly waiting for a response/file?). There's no response or error whatsoever. Running it with Python interpreter alone causes it to break whenever I input anything.

![github](https://user-images.githubusercontent.com/16601553/30274749-284320e2-96d5-11e7-9ae0-aa4e21be7bdc.png)

**Expectations**

According to latest patch and docs pystrix 1.1.0 should work out of the box for any Python 3 (3.4+) scripts. I also used both my script and [readthedocs](http://pystrix.readthedocs.io/en/latest/examples/agi.html) simple example. Same behavior in Python 3.

**Workaround**

In order to use this lib I had to 'downgrade' my script to Python 2.7 syntax and call it with Python 2.7 interpreter. Everything works fine now. Am I noobing somewhere? I did spend quite some time reading pystrix base code, asterisk logs, etc. Besides the aforementioned error, nothing seems wrong. Any ideias?

**Comment by clearinterface** [comment]
hey there, sorry, did not see this issue until now. let me take a look and see if i can duplicate the issue and get back to you on it

**Comment by marsoguti** [comment]
hi @xzjkya sorry for the late response, i didn't have time until now to review this issue. 

I have been trying to replicate it, but i didn't seem to be able to.  Can you help me with a little more of information? for example, how your call_agi.py script looks like? or something else you can tell me to see where that everlasting loop might being happening?  

Thanks a lot, and sorry again for the late response.

**Comment by marsoguti** [comment]
hi @xzjkya I think I finally was able to replicate the issue, and it's apparently fixed.  Changes are up and a new version of the package has been created and uploaded (1.1.1 - ), please update your version and let me know if it works for you now, or if you find any new issue.

**Comment by xzjkya** [comment]
I'll find sometime next week to test it extensively with Python 3 (same environment as I had before) and let you guys know. Thanks and great work!
