### ISSUE TITLE
Python 3.5   -  TypeError: can only concatenate list (not "dict_items") to list

### ISSUE THREAD

**Issue by migue56** [IVRTech/pystrix#21]
When I use AMI with Python 3.5. I have an issue  when concatenate  list:
```
  File "example-ami.py", line 137, in <module>
    ami_core = AMICore()
  File "example-ami.py", line 35, in __init__
    challenge_response = self._manager.send_action(pystrix.ami.core.Challenge())
  File "pystrix/ami/ami.py", line 502, in send_action
    (command, action_id) = request.build_request(action_id and str(action_id), self._get_host_action_id, **kwargs)
  File "pystrix/ami/ami.py", line 894, in build_request
    for (key, value) in [(k, v) for (k, v) in self.items() if not k in (KEY_ACTION, KEY_ACTIONID)] + kwargs.items():
TypeError: can only concatenate list (not "dict_items") to list
```

I have been changed that line with` list( kwargs.items()) `, but that doesn't change it and I get other issue:

```
    self._socket.sendall(message)
TypeError: a bytes-like object is required, not 'str'

```
I have tried to change with the encode string, but Asterisk doesn't response it

 ```
        if isinstance(message,str):
                 message =  message.encode()
```

Message: ` b'Action: Challenge\r\nAuthType: MD5\r\nActionID: test-lx-W9WGU-00000001\r\n\r\n'`

**Comment by xzjkya** [comment]
@migue56 could you be more specific about the source code? Not sure what your purpose is and how you're trying to achieve it.

**Comment by migue56** [comment]
@xzjkya it is a issue tried to use python 3.5, because this version does not accept concatenate list and dict. My purpose was  let you know about  this issue, and in the future I could help you about it.
