### ISSUE TITLE
Pystrix not executing custom code and function in Python

### ISSUE THREAD

**Issue by qasimali000** [IVRTech/pystrix#30]
Hi

I'm trying to execute some code over the AGI using Pystrix during the call and it skips the code and goes directly to the hangup.

Please help.

Thanks

**Comment by karthicraghupathi** [comment]
You have not provided much by way of code samples or any errors you are encountering.

Please post a small sample of your code which reproduces your issue so we can attempt to troubleshoot your issue. Also some description of what you expect to happen and what is actually happening will help.
